# Generated by Django 5.0.2 on 2024-02-28 04:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('text', models.TextField(max_length=500)),
                ('due', models.DateTimeField(default=datetime.datetime(2024, 2, 28, 4, 46, 9, 423065, tzinfo=datetime.timezone.utc))),
            ],
        ),
    ]
