# Generated by Django 5.0.2 on 2024-03-05 06:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_todo_user_alter_todo_due'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='start',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
