# Generated by Django 5.0.2 on 2024-03-09 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_remove_todo_categorys_alter_todo_text_todo_categorys'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='color',
            field=models.CharField(choices=[('#333333', 'light_black'), ('light_green', '#66ff66'), ('light_blue', '#66ffff'), ('deep_blue', '#3333cc'), ('red', '#ff0000')], default='#66ffff', max_length=11),
        ),
    ]
