# Generated by Django 5.0.2 on 2024-03-11 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0007_rename_categorys_todo_category_alter_category_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='priority',
            field=models.IntegerField(choices=[(1, 'high'), (2, 'middle'), (3, 'low')], default=2),
        ),
    ]
