# Generated by Django 5.0.2 on 2025-02-24 05:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0009_alter_category_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='progress',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
    ]
