# Generated by Django 5.0.2 on 2025-02-24 08:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0010_todo_progress'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('within_due_lte20_num', models.IntegerField(default=0)),
                ('within_due_lte40_num', models.IntegerField(default=0)),
                ('within_due_lte60_num', models.IntegerField(default=0)),
                ('within_due_lte80_num', models.IntegerField(default=0)),
                ('within_due_lte100_num', models.IntegerField(default=0)),
                ('out_due_num', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
